version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: liquidDemocracy
      MYSQL_USER: lduser
      MYSQL_PASSWORD: ldpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
